In [1]:
# 필요한 라이브러리 호출

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn

In [3]:
# 파일 로드
df = pd.read_csv('C:/myPyCode/data/car.csv')
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [4]:
# 데이터 확인중
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [6]:
# object 숫자 확인
df.info() # name, fuel, seller_type, transmission, owner, mileage, engine,
# max_power, torque, 이상 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [8]:
# 소수점 축약
pd.options.display.float_format = "{:.4f}".format
df.describe()

year  selling_price    km_driven     seats
count 8128.0000      8128.0000    8128.0000 7907.0000
mean  2013.8040    638271.8077   69819.5108    5.4167
std      4.0442    806253.4035   56550.5550    0.9596
min   1983.0000     29999.0000       1.0000    2.0000
25%   2011.0000    254999.0000   35000.0000    5.0000
50%   2015.0000    450000.0000   60000.0000    5.0000
75%   2017.0000    675000.0000   98000.0000    5.0000
max   2020.0000  10000000.0000 2360457.0000   14.0000

In [9]:
# 결측치 확인
df.isnull().sum() # 5 feature

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [11]:
# 데이터 전처리 시작
# 명목형 변수 처리

df.describe(include='O') # 총 9개

name    fuel seller_type transmission        owner  \
count                     8128    8128        8128         8128         8128   
unique                    2058       4           3            2            5   
top     Maruti Swift Dzire VDI  Diesel  Individual       Manual  First Owner   
freq                       129    4402        6766         7078         5289   

          mileage   engine max_power          torque  
count        7907     7907      7913            7906  
unique        393      121       322             441  
top     18.9 kmpl  1248 CC    74 bhp  190Nm@ 2000rpm  
freq          225     1017       377             530

In [12]:
# engine 피쳐부터 시작

# value 종류부터 확인

df.engine.unique() # CC라는 단위가 존재

array(['1248 CC', '1498 CC', '1497 CC', '1396 CC', '1298 CC', '1197 CC',
       '1061 CC', '796 CC', '1364 CC', '1399 CC', '1461 CC', '993 CC',
       nan, '1198 CC', '1199 CC', '998 CC', '1591 CC', '2179 CC',
       '1368 CC', '2982 CC', '2494 CC', '2143 CC', '2477 CC', '1462 CC',
       '2755 CC', '1968 CC', '1798 CC', '1196 CC', '1373 CC', '1598 CC',
       '1998 CC', '1086 CC', '1194 CC', '1172 CC', '1405 CC', '1582 CC',
       '999 CC', '2487 CC', '1999 CC', '3604 CC', '2987 CC', '1995 CC',
       '1451 CC', '1969 CC', '2967 CC', '2497 CC', '1797 CC', '1991 CC',
       '2362 CC', '1493 CC', '1599 CC', '1341 CC', '1794 CC', '799 CC',
       '1193 CC', '2696 CC', '1495 CC', '1186 CC', '1047 CC', '2498 CC',
       '2956 CC', '2523 CC', '1120 CC', '624 CC', '1496 CC', '1984 CC',
       '2354 CC', '814 CC', '793 CC', '1799 CC', '936 CC', '1956 CC',
       '1997 CC', '1499 CC', '1948 CC', '2997 CC', '2489 CC', '2499 CC',
       '2609 CC', '2953 CC', '1150 CC', '1994 CC', '1388 CC', '152

In [13]:
# 메서드 str.split(expand)를 통해 컬럼 분리

df.engine.str.split(expand=True)

0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [14]:
# 컬럼 자체의 이름 설정

df[['engine','engine_unit']] = df.engine.str.split(expand=True)
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage engine  \
0     Individual       Manual           First Owner   23.4 kmpl   1248   
1     Individual       Manual          Second Owner  21.14 kmpl   1498   
2     Individual       Manual           Third Owner   17.7 kmpl   1497   
3     Individual       Manual           First Owner   23.0 kmpl   1396   
4     Individual       Manual           First Owner   16.1 kmpl   1298   
...          ...          ...                   ...         ...    ...   
8123  Individual       Manual           First Owner   18.5 kmpl   1197   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl   1493   
8125  Individual       Manual           First Owner   19.3 kmpl   1248   
8126  Individual       Manual           First Owner  23.57 kmpl   1396   
8127  Individual       Manual           First Owner  23.57 kmpl   1396   

       max_power                     torque  seats engine_unit  
0         74 bhp             190Nm@ 2000rpm 5.0000          CC  
1     103.52 bhp        250Nm@ 1500-2500rpm 5.0000          CC  
2         78 bhp      12.7@ 2,700(kgm@ rpm) 5.0000          CC  
3         90 bhp   22.4 kgm at 1750-2750rpm 5.0000          CC  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm) 5.0000          CC  
...          ...                        ...    ...         ...  
8123   82.85 bhp           113.7Nm@ 4000rpm 5.0000          CC  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm) 5.0000          CC  
8125    73.9 bhp             190Nm@ 2000rpm 5.0000          CC  
8126      70 bhp        140Nm@ 1800-3000rpm 5.0000          CC  
8127      70 bhp        140Nm@ 1800-3000rpm 5.0000          CC  

[8128 rows x 14 columns]

In [15]:
# engine을 실수형을 변형

df.engine = df.engine.astype('float32')
df.engine

0      1248.0000
1      1498.0000
2      1497.0000
3      1396.0000
4      1298.0000
          ...   
8123   1197.0000
8124   1493.0000
8125   1248.0000
8126   1396.0000
8127   1396.0000
Name: engine, Length: 8128, dtype: float32

In [16]:
# (주의) 단위가 써있는 unit 행은 삭제(drop)

df.drop('engine_unit', axis = 1, inplace = True)
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage    engine  \
0     Individual       Manual           First Owner   23.4 kmpl 1248.0000   
1     Individual       Manual          Second Owner  21.14 kmpl 1498.0000   
2     Individual       Manual           Third Owner   17.7 kmpl 1497.0000   
3     Individual       Manual           First Owner   23.0 kmpl 1396.0000   
4     Individual       Manual           First Owner   16.1 kmpl 1298.0000   
...          ...          ...                   ...         ...       ...   
8123  Individual       Manual           First Owner   18.5 kmpl 1197.0000   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl 1493.0000   
8125  Individual       Manual           First Owner   19.3 kmpl 1248.0000   
8126  Individual       Manual           First Owner  23.57 kmpl 1396.0000   
8127  Individual       Manual           First Owner  23.57 kmpl 1396.0000   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm 5.0000  
1     103.52 bhp        250Nm@ 1500-2500rpm 5.0000  
2         78 bhp      12.7@ 2,700(kgm@ rpm) 5.0000  
3         90 bhp   22.4 kgm at 1750-2750rpm 5.0000  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm) 5.0000  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm 5.0000  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm) 5.0000  
8125    73.9 bhp             190Nm@ 2000rpm 5.0000  
8126      70 bhp        140Nm@ 1800-3000rpm 5.0000  
8127      70 bhp        140Nm@ 1800-3000rpm 5.0000  

[8128 rows x 13 columns]

In [17]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [18]:
# max_power(최대 출력) 처리 시작

df.max_power.head() # bhp 단위 수정

0        74 bhp
1    103.52 bhp
2        78 bhp
3        90 bhp
4      88.2 bhp
Name: max_power, dtype: object

In [19]:
df.max_power.unique() # 데이터 종류 확인

array(['74 bhp', '103.52 bhp', '78 bhp', '90 bhp', '88.2 bhp',
       '81.86 bhp', '57.5 bhp', '37 bhp', '67.1 bhp', '68.1 bhp',
       '108.45 bhp', '60 bhp', '73.9 bhp', nan, '67 bhp', '82 bhp',
       '88.5 bhp', '46.3 bhp', '88.73 bhp', '64.1 bhp', '98.6 bhp',
       '88.8 bhp', '83.81 bhp', '83.1 bhp', '47.3 bhp', '73.8 bhp',
       '34.2 bhp', '35 bhp', '81.83 bhp', '40.3 bhp', '121.3 bhp',
       '138.03 bhp', '160.77 bhp', '117.3 bhp', '116.3 bhp', '83.14 bhp',
       '67.05 bhp', '168.5 bhp', '100 bhp', '120.7 bhp', '98.63 bhp',
       '175.56 bhp', '103.25 bhp', '171.5 bhp', '100.6 bhp', '174.33 bhp',
       '187.74 bhp', '170 bhp', '78.9 bhp', '88.76 bhp', '86.8 bhp',
       '108.495 bhp', '108.62 bhp', '93.7 bhp', '103.6 bhp', '98.59 bhp',
       '189 bhp', '67.04 bhp', '68.05 bhp', '58.2 bhp', '82.85 bhp',
       '81.80 bhp', '73 bhp', '120 bhp', '94.68 bhp', '160 bhp', '65 bhp',
       '155 bhp', '69.01 bhp', '126.32 bhp', '138.1 bhp', '83.8 bhp',
       '126.2 bhp', '98.

In [20]:
# bhp 단일 value가 존재하여 전처리 필요

In [21]:
df[['max_power','max_power_unit']] = df.max_power.str.split(expand=True)

In [22]:
df

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage    engine  \
0     Individual       Manual           First Owner   23.4 kmpl 1248.0000   
1     Individual       Manual          Second Owner  21.14 kmpl 1498.0000   
2     Individual       Manual           Third Owner   17.7 kmpl 1497.0000   
3     Individual       Manual           First Owner   23.0 kmpl 1396.0000   
4     Individual       Manual           First Owner   16.1 kmpl 1298.0000   
...          ...          ...                   ...         ...       ...   
8123  Individual       Manual           First Owner   18.5 kmpl 1197.0000   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl 1493.0000   
8125  Individual       Manual           First Owner   19.3 kmpl 1248.0000   
8126  Individual       Manual           First Owner  23.57 kmpl 1396.0000   
8127  Individual       Manual           First Owner  23.57 kmpl 1396.0000   

     max_power                     torque  seats max_power_unit  
0           74             190Nm@ 2000rpm 5.0000            bhp  
1       103.52        250Nm@ 1500-2500rpm 5.0000            bhp  
2           78      12.7@ 2,700(kgm@ rpm) 5.0000            bhp  
3           90   22.4 kgm at 1750-2750rpm 5.0000            bhp  
4         88.2      11.5@ 4,500(kgm@ rpm) 5.0000            bhp  
...        ...                        ...    ...            ...  
8123     82.85           113.7Nm@ 4000rpm 5.0000            bhp  
8124       110  24@ 1,900-2,750(kgm@ rpm) 5.0000            bhp  
8125      73.9             190Nm@ 2000rpm 5.0000            bhp  
8126        70        140Nm@ 1800-3000rpm 5.0000            bhp  
8127        70        140Nm@ 1800-3000rpm 5.0000            bhp  

[8128 rows x 14 columns]

In [23]:
# 직접 정의한 타입 변환 함수를 통해 error를 처리
# float로 변환
def handle_float(value):
    try:
        return float(value)
    except ValueError:
        return np.NaN

In [24]:
df.max_power = df.max_power.apply(handle_float)

In [25]:
df.max_power

0       74.0000
1      103.5200
2       78.0000
3       90.0000
4       88.2000
         ...   
8123    82.8500
8124   110.0000
8125    73.9000
8126    70.0000
8127    70.0000
Name: max_power, Length: 8128, dtype: float64

In [26]:
df.isnull().sum()

name                0
year                0
selling_price       0
km_driven           0
fuel                0
seller_type         0
transmission        0
owner               0
mileage           221
engine            221
max_power         216
torque            222
seats             221
max_power_unit    222
dtype: int64

In [27]:
# 단위는 불필요하니 삭제
# (주의)
df.drop('max_power_unit', axis = 1, inplace=True)

In [28]:
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage    engine  max_power  \
0  Individual       Manual   First Owner   23.4 kmpl 1248.0000    74.0000   
1  Individual       Manual  Second Owner  21.14 kmpl 1498.0000   103.5200   
2  Individual       Manual   Third Owner   17.7 kmpl 1497.0000    78.0000   
3  Individual       Manual   First Owner   23.0 kmpl 1396.0000    90.0000   
4  Individual       Manual   First Owner   16.1 kmpl 1298.0000    88.2000   

                     torque  seats  
0            190Nm@ 2000rpm 5.0000  
1       250Nm@ 1500-2500rpm 5.0000  
2     12.7@ 2,700(kgm@ rpm) 5.0000  
3  22.4 kgm at 1750-2750rpm 5.0000  
4     11.5@ 4,500(kgm@ rpm) 5.0000

In [29]:
# mileage 데이터 처리 시작

df.mileage.unique()

array(['23.4 kmpl', '21.14 kmpl', '17.7 kmpl', '23.0 kmpl', '16.1 kmpl',
       '20.14 kmpl', '17.3 km/kg', '23.59 kmpl', '20.0 kmpl',
       '19.01 kmpl', '17.3 kmpl', '19.3 kmpl', nan, '18.9 kmpl',
       '18.15 kmpl', '24.52 kmpl', '19.7 kmpl', '22.54 kmpl', '21.0 kmpl',
       '25.5 kmpl', '26.59 kmpl', '21.5 kmpl', '20.3 kmpl', '21.4 kmpl',
       '24.7 kmpl', '18.2 kmpl', '16.8 kmpl', '24.3 kmpl', '14.0 kmpl',
       '18.6 kmpl', '33.44 km/kg', '23.95 kmpl', '17.0 kmpl',
       '20.63 kmpl', '13.93 kmpl', '16.0 kmpl', '17.8 kmpl', '18.5 kmpl',
       '12.55 kmpl', '12.99 kmpl', '14.8 kmpl', '13.5 kmpl', '26.0 kmpl',
       '20.65 kmpl', '27.3 kmpl', '11.36 kmpl', '17.68 kmpl',
       '14.28 kmpl', '18.53 kmpl', '14.84 kmpl', '21.12 kmpl',
       '20.36 kmpl', '21.27 kmpl', '18.16 kmpl', '22.0 kmpl', '25.1 kmpl',
       '20.51 kmpl', '21.66 kmpl', '25.2 kmpl', '22.9 kmpl', '16.02 kmpl',
       '20.54 kmpl', '22.77 kmpl', '15.71 kmpl', '23.1 kmpl',
       '19.02 kmpl', '19.81 kmpl'

In [30]:
# 배경 지식 필요 (kmpl)

df[['mileage','mileage_unit']]= df.mileage.str.split(expand=True)
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner mileage    engine  max_power  \
0  Individual       Manual   First Owner    23.4 1248.0000    74.0000   
1  Individual       Manual  Second Owner   21.14 1498.0000   103.5200   
2  Individual       Manual   Third Owner    17.7 1497.0000    78.0000   
3  Individual       Manual   First Owner    23.0 1396.0000    90.0000   
4  Individual       Manual   First Owner    16.1 1298.0000    88.2000   

                     torque  seats mileage_unit  
0            190Nm@ 2000rpm 5.0000         kmpl  
1       250Nm@ 1500-2500rpm 5.0000         kmpl  
2     12.7@ 2,700(kgm@ rpm) 5.0000         kmpl  
3  22.4 kgm at 1750-2750rpm 5.0000         kmpl  
4     11.5@ 4,500(kgm@ rpm) 5.0000         kmpl

In [31]:
df.mileage = df.mileage.astype('float32')
df.mileage

0      23.4000
1      21.1400
2      17.7000
3      23.0000
4      16.1000
         ...  
8123   18.5000
8124   16.8000
8125   19.3000
8126   23.5700
8127   23.5700
Name: mileage, Length: 8128, dtype: float32

In [32]:
df.fuel.unique() # fuel 4종류에 km/l과 km/kg가 대응함

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [33]:
df.fuel[df.mileage_unit == 'kmpl'].unique() # kmpl : diesel, petrol 대응

array(['Diesel', 'Petrol'], dtype=object)

In [34]:
df.fuel[df.mileage_unit == 'km/kg'].unique() # km/kg에 lpg, cng가 대응

array(['LPG', 'CNG'], dtype=object)

In [37]:
# 현재 유가 확인

fuels = {
    'Petrol' : 80.4,
    'Diesel' : 73.5,
    'LPG' : 40.8,
    'CNG' : 44.2
}
fuels

{'Petrol': 80.4, 'Diesel': 73.5, 'LPG': 40.8, 'CNG': 44.2}

In [38]:
# map으로 딕셔너리 제작
df.fuel.map(fuels)

0      73.5000
1      73.5000
2      80.4000
3      73.5000
4      80.4000
         ...  
8123   80.4000
8124   73.5000
8125   73.5000
8126   73.5000
8127   73.5000
Name: fuel, Length: 8128, dtype: float64

In [39]:
# 연비
df.mileage / df.fuel.map(fuels)

0      0.3184
1      0.2876
2      0.2201
3      0.3129
4      0.2002
        ...  
8123   0.2301
8124   0.2286
8125   0.2626
8126   0.3207
8127   0.3207
Length: 8128, dtype: float64

In [40]:
# apply로 행이 갖고 있는 열 사용

def handle_mileage(row):
    return row.mileage/fuels[row.fuel]

In [42]:
df.mileage = df.apply(handle_mileage, axis=1)
df.mileage

0      0.0043
1      0.0039
2      0.0027
3      0.0043
4      0.0025
        ...  
8123   0.0029
8124   0.0031
8125   0.0036
8126   0.0044
8127   0.0044
Name: mileage, Length: 8128, dtype: float64

In [43]:
# unit 행 삭제 주의

df.drop('mileage_unit', axis=1, inplace= True)

In [44]:
# torque 전처리
df.torque.unique()

array(['190Nm@ 2000rpm', '250Nm@ 1500-2500rpm', '12.7@ 2,700(kgm@ rpm)',
       '22.4 kgm at 1750-2750rpm', '11.5@ 4,500(kgm@ rpm)',
       '113.75nm@ 4000rpm', '7.8@ 4,500(kgm@ rpm)', '59Nm@ 2500rpm',
       '170Nm@ 1800-2400rpm', '160Nm@ 2000rpm', '248Nm@ 2250rpm',
       '78Nm@ 4500rpm', nan, '84Nm@ 3500rpm', '115Nm@ 3500-3600rpm',
       '200Nm@ 1750rpm', '62Nm@ 3000rpm', '219.7Nm@ 1500-2750rpm',
       '114Nm@ 3500rpm', '115Nm@ 4000rpm', '69Nm@ 3500rpm',
       '172.5Nm@ 1750rpm', '6.1kgm@ 3000rpm', '114.7Nm@ 4000rpm',
       '60Nm@ 3500rpm', '90Nm@ 3500rpm', '151Nm@ 4850rpm',
       '104Nm@ 4000rpm', '320Nm@ 1700-2700rpm', '250Nm@ 1750-2500rpm',
       '145Nm@ 4600rpm', '146Nm@ 4800rpm', '343Nm@ 1400-3400rpm',
       '200Nm@ 1400-3400rpm', '200Nm@ 1250-4000rpm',
       '400Nm@ 2000-2500rpm', '138Nm@ 4400rpm', '360Nm@ 1200-3400rpm',
       '200Nm@ 1200-3600rpm', '380Nm@ 1750-2500rpm', '173Nm@ 4000rpm',
       '400Nm@ 1750-3000rpm', '400Nm@ 1400-2800rpm',
       '200Nm@ 1750-3000rp

In [47]:
# unit을 추출하기 위한 함수 저으이

def handle_torque_unit(x):
    if 'NM' in str(x):
        return 'NM'
    if 'KGM' in str(x):
        return 'kgm'

In [48]:
df.torque.apply(handle_torque_unit)

0       None
1       None
2       None
3       None
4       None
        ... 
8123    None
8124    None
8125    None
8126    None
8127    None
Name: torque, Length: 8128, dtype: object

In [49]:
# torque unit을 대문자 변환

df['torque_unit'] = df.torque.str.upper().apply(handle_torque_unit)

In [53]:
# 100보다 큰 unit값 조회

df[df.torque_unit.isna()].torque.unique()

array([], dtype=object)

In [55]:
df[df['torque_unit']=='Nm'].torque

13      NaN
31      NaN
78      NaN
87      NaN
119     NaN
       ... 
7846    NaN
7996    NaN
8009    NaN
8068    NaN
8103    NaN
Name: torque, Length: 234, dtype: object

In [56]:
df[df['torque_unit']=='kgm'].torque

2           12.7@ 2,700(kgm@ rpm)
3        22.4 kgm at 1750-2750rpm
4           11.5@ 4,500(kgm@ rpm)
6            7.8@ 4,500(kgm@ rpm)
17       22.4 kgm at 1750-2750rpm
                  ...            
8082        16.3@ 2,000(kgm@ rpm)
8104        13.5@ 4,800(kgm@ rpm)
8105             11.3kgm@ 4700rpm
8113    20.4@ 1400-3400(kgm@ rpm)
8124    24@ 1,900-2,750(kgm@ rpm)
Name: torque, Length: 504, dtype: object

In [57]:
# 결측치 강제처리
df.torque_unit.fillna('Nm', inplace=True)

In [58]:
df.torque_unit.unique()

array(['NM', 'kgm', 'Nm'], dtype=object)

In [59]:
# 정규표현식 사용

df.torque.str.extract("([\d\.]+)").astype('float') # 실수형으로 변환

0
0    190.0000
1    250.0000
2     12.7000
3     22.4000
4     11.5000
...       ...
8123 113.7000
8124  24.0000
8125 190.0000
8126 140.0000
8127 140.0000

[8128 rows x 1 columns]

In [60]:
# 그외에는 torque에서 삭제

df.torque = df.torque.str.extract("([\d\.]+)").astype('float')
df.torque

0      190.0000
1      250.0000
2       12.7000
3       22.4000
4       11.5000
         ...   
8123   113.7000
8124    24.0000
8125   190.0000
8126   140.0000
8127   140.0000
Name: torque, Length: 8128, dtype: float64

In [61]:
# 9.8066 kgm = 1Nm
# kgm을 Nm으로 만드는 함수 정의
def handle_torque_trans(x):
    if x.torque_unit =='kgm':
        return x.torque * 9.8066
    return x.torque

In [62]:
# apply로 적용

df.torque = df.apply(handle_torque_trans, axis = 1)
df.torque

0      190.0000
1      250.0000
2      124.5438
3      219.6678
4      112.7759
         ...   
8123   113.7000
8124   235.3584
8125   190.0000
8126   140.0000
8127   140.0000
Name: torque, Length: 8128, dtype: float64

In [63]:
# unit행은 불필요하므로 삭제 (주의)

df.drop('torque_unit', axis = 1, inplace = True)

In [64]:
# name 수정

df.name.value_counts()

Maruti Swift Dzire VDI                             129
Maruti Alto 800 LXI                                 82
Maruti Alto LXi                                     71
BMW X4 M Sport X xDrive20d                          62
Maruti Swift VDI                                    61
                                                  ... 
Skoda Fabia 1.4 TDI Ambiente                         1
Mahindra Scorpio VLX 2WD AT BSIII                    1
Renault KWID Climber 1.0 AMT                         1
Mahindra XUV300 W8 Option Dual Tone Diesel BSIV      1
Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV         1
Name: name, Length: 2058, dtype: int64

In [65]:
df.name.unique()

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', ..., 'Tata Nexon 1.5 Revotorq XT',
       'Ford Freestyle Titanium Plus Diesel BSIV',
       'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV'], dtype=object)

In [67]:
df.name = df.name.str.split(expand=True)[0]
df.name

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...   
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: name, Length: 8128, dtype: object

In [68]:
df.name.unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [69]:
# Land Rover 브랜드가 land만 조회됨
# replace로 교체
df.name = df.name.replace('Land', 'Land Rover')
df.name.unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land Rover', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [70]:
# 결측치 수정

df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        216
torque           222
seats            221
dtype: int64

In [71]:
# 결측치는 제거

df.dropna(inplace=True)

In [72]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [74]:
# 더미 변수 생성

car_columns = df.describe(include=['O']).columns
car_columns

Index(['name', 'fuel', 'seller_type', 'transmission', 'owner'], dtype='object')

In [75]:
# get_dummies

df = pd.get_dummies(df, columns = car_columns , drop_first= True)
df

year  selling_price  km_driven  mileage    engine  max_power   torque  \
0     2014         450000     145500   0.0043 1248.0000    74.0000 190.0000   
1     2014         370000     120000   0.0039 1498.0000   103.5200 250.0000   
2     2006         158000     140000   0.0027 1497.0000    78.0000 124.5438   
3     2010         225000     127000   0.0043 1396.0000    90.0000 219.6678   
4     2007         130000     120000   0.0025 1298.0000    88.2000 112.7759   
...    ...            ...        ...      ...       ...        ...      ...   
8123  2013         320000     110000   0.0029 1197.0000    82.8500 113.7000   
8124  2007         135000     119000   0.0031 1493.0000   110.0000 235.3584   
8125  2009         382000     120000   0.0036 1248.0000    73.9000 190.0000   
8126  2013         290000      25000   0.0044 1396.0000    70.0000 140.0000   
8127  2013         290000      25000   0.0044 1396.0000    70.0000 140.0000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0    5.0000           0          0  ...            1         0            0   
1    5.0000           0          0  ...            1         0            0   
2    5.0000           0          0  ...            0         0            1   
3    5.0000           0          0  ...            1         0            0   
4    5.0000           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
8123 5.0000           0          0  ...            0         0            1   
8124 5.0000           0          0  ...            1         0            0   
8125 5.0000           0          0  ...            1         0            0   
8126 5.0000           0          0  ...            1         0            0   
8127 5.0000           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
8123                       1                             0   
8124                       1                             0   
8125                       1                             0   
8126                       1                             0   
8127                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
8123                    1                           0                   0   
8124                    1                           1                   0   
8125                    1                           0                   0   
8126                    1                           0                   0   
8127                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
8123                     0                  0  
8124                     0                  0  
8125  

In [76]:
df # 더미 확인

year  selling_price  km_driven  mileage    engine  max_power   torque  \
0     2014         450000     145500   0.0043 1248.0000    74.0000 190.0000   
1     2014         370000     120000   0.0039 1498.0000   103.5200 250.0000   
2     2006         158000     140000   0.0027 1497.0000    78.0000 124.5438   
3     2010         225000     127000   0.0043 1396.0000    90.0000 219.6678   
4     2007         130000     120000   0.0025 1298.0000    88.2000 112.7759   
...    ...            ...        ...      ...       ...        ...      ...   
8123  2013         320000     110000   0.0029 1197.0000    82.8500 113.7000   
8124  2007         135000     119000   0.0031 1493.0000   110.0000 235.3584   
8125  2009         382000     120000   0.0036 1248.0000    73.9000 190.0000   
8126  2013         290000      25000   0.0044 1396.0000    70.0000 140.0000   
8127  2013         290000      25000   0.0044 1396.0000    70.0000 140.0000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0    5.0000           0          0  ...            1         0            0   
1    5.0000           0          0  ...            1         0            0   
2    5.0000           0          0  ...            0         0            1   
3    5.0000           0          0  ...            1         0            0   
4    5.0000           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
8123 5.0000           0          0  ...            0         0            1   
8124 5.0000           0          0  ...            1         0            0   
8125 5.0000           0          0  ...            1         0            0   
8126 5.0000           0          0  ...            1         0            0   
8127 5.0000           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
8123                       1                             0   
8124                       1                             0   
8125                       1                             0   
8126                       1                             0   
8127                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
8123                    1                           0                   0   
8124                    1                           1                   0   
8125                    1                           0                   0   
8126                    1                           0                   0   
8127                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
8123                     0                  0  
8124                     0                  0  
8125  

In [77]:
# 훈련셋/시험셋 분리 시작

In [79]:
# 패키지 호출

from sklearn.model_selection import train_test_split

In [80]:
X = df.drop('selling_price', axis = 1)
y = df['selling_price']

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)


In [84]:
# 모델 적용

from sklearn.ensemble import RandomForestRegressor

In [85]:
# model 정의
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [86]:
# 훈련셋 예측

trainpred = model.predict(X_train)
testpred = model.predict(X_test)

In [87]:
# 결정계수 호출

from sklearn.metrics import mean_squared_error

In [88]:
mean_squared_error(y_train, trainpred, squared=False) # 훈련

51722.08977105568

In [89]:
mean_squared_error(y_test, testpred, squared=False) # 시험

# overfitting 추론

176899.7678991943

In [90]:
# KFold 교차검증 시작

from sklearn.model_selection import KFold

In [91]:
kfold = KFold()

In [93]:
# 인덱스 정리 시작

df.index # 빈 인덱스 정리필요

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            8118, 8119, 8120, 8121, 8122, 8123, 8124, 8125, 8126, 8127],
           dtype='int64', length=7906)

In [95]:
df.reset_index()
df.reset_index(drop=True, inplace=True)

In [96]:
df.index

RangeIndex(start=0, stop=7906, step=1)

In [97]:
kf = KFold(n_splits = 5)
# kfold 교차검증 5회차 사용

In [98]:
X = df.drop('selling_price', axis = 1)
y = df['selling_price'] # 변수들 재소환

In [99]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [100]:
list(kf.split(X))

[(array([1582, 1583, 1584, ..., 7903, 7904, 7905]),
  array([   0,    1,    2, ..., 1579, 1580, 1581])),
 (array([   0,    1,    2, ..., 7903, 7904, 7905]),
  array([1582, 1583, 1584, ..., 3160, 3161, 3162])),
 (array([   0,    1,    2, ..., 7903, 7904, 7905]),
  array([3163, 3164, 3165, ..., 4741, 4742, 4743])),
 (array([   0,    1,    2, ..., 7903, 7904, 7905]),
  array([4744, 4745, 4746, ..., 6322, 6323, 6324])),
 (array([   0,    1,    2, ..., 6322, 6323, 6324]),
  array([6325, 6326, 6327, ..., 7903, 7904, 7905]))]

In [102]:
# 함수 정의

for i, j in kf.split(X):
    print(f'i : {i}')
    print(f'j : {i}')

i : [1582 1583 1584 ... 7903 7904 7905]
j : [1582 1583 1584 ... 7903 7904 7905]
i : [   0    1    2 ... 7903 7904 7905]
j : [   0    1    2 ... 7903 7904 7905]
i : [   0    1    2 ... 7903 7904 7905]
j : [   0    1    2 ... 7903 7904 7905]
i : [   0    1    2 ... 7903 7904 7905]
j : [   0    1    2 ... 7903 7904 7905]
i : [   0    1    2 ... 6322 6323 6324]
j : [   0    1    2 ... 6322 6323 6324]


In [103]:
# 순서대로 반복시키는 함수 정의

train_rmse_total = []
test_rmse_total= []

In [105]:
# 반복문 정의
train_rmse_total = []
test_rmse_total= []


for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(random_state=10)
    model.fit(X_train, y_train)
    
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred, squared=False) # 훈련셋 rmse 계산
    test_rmse = mean_squared_error(y_test, test_pred, squared= False) # 시험셋 rnmse 계산
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    
    # 다소 시간 소요

In [106]:
# 점수 종료

train_rmse_total, test_rmse_total

([52205.055231337734,
  53956.30570901482,
  52612.119480985224,
  52525.266704924805,
  54467.66782930233],
 [165438.5746333864,
  132049.9828035612,
  123546.11913847631,
  147895.8826855663,
  143159.43371203632])

In [107]:
sum(train_rmse_total) / len(train_rmse_total)# 평균

53153.28299111298

In [108]:
sum(test_rmse_total) / len(test_rmse_total) # test 평균

142417.9985946053

In [109]:
# 하이퍼 패러미터 조정

# 반복문 정의
train_rmse_total = []
test_rmse_total= []


for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(
        n_estimators = 100,
        max_depth = 50,
        min_samples_split = 5,
        min_samples_leaf = 1,
        n_jobs = -1,
        random_state = 10)
    
    model.fit(X_train, y_train)
    
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred, squared=False) # 훈련셋 rmse 계산
    test_rmse = mean_squared_error(y_test, test_pred, squared= False) # 시험셋 rnmse 계산
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    
    # 다소 시간 소요

In [116]:
# 실제값, 예측값 비교

"hyper_parameter train rmse",sum(train_rmse_total)/len(train_rmse_total)

('hyper_parameter train rmse', 66474.13941841603)

In [117]:
"hyper_parameter test rmse",sum(test_rmse_total)/len(test_rmse_total)

('hyper_parameter test rmse', 142674.6086535202)

In [118]:
# 하이퍼 패러미터로 예측 최적화 . regression 문제 종료.